# Generated by Django 3.1.14 on 2022-10-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_auto_20221002_0011'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['travel_time'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
        migrations.AddField(
            model_name='train',
            name='to_city',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='trains.city', verbose_name='В какой город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='travel_time',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Время в пути'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='train',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='trains.city', verbose_name='Из какого города'),
        ),
        migrations.CreateModel(
            name='TrainTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Номер поезда')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.city', verbose_name='Из какого города')),
            ],
        ),
    ]
