# Generated by Django 3.1.14 on 2022-10-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_auto_20221002_0011'),
        ('trains', '0002_auto_20221002_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traintest',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='trains.city', verbose_name='Из какого города'),
        ),
    ]
